export const SECTION_FIELDS: Record<string, string[]> = {
  school: [
    'legalName',
    'shortName',
    'board',
    'affiliationNumber',
    'udiseCode',
    'primaryPhone',
    'secondaryPhone',
    'contactEmail',
    'website',
    'addressLine1',
    'addressLine2',
    'city',
    'state',
    'postalCode',
    'country',
  ],
  academic: [
    'workingWeek',
    'weekStart',
    'termNaming',
    'rollNumberScope',
    'academicLockingEnabled',
  ],
  'student-identity': [
    'studentIdFormat',
    'admissionNumberFormat',
    'rollNumberFormat',
  ],
  attendance: [
    'attendanceLockEnabled',
    'attendanceLockHours',
    'attendanceCorrectionAllowed',
    'attendanceCorrectionReasonRequired',
    'attendancePrincipalOverride',
    'teacherGeofenceEnabled',
    'teacherGeofenceRadiusMeters',
  ],
  fees: [
    'feeCurrency',
    'feePrecision',
    'feeRoundingRule',
    'allowPartialPayment',
    'allowAdvancePayment',
    'lateFeeEnabled',
    'lateFeeGraceDays',
    'autoGenerateReceipt',
    'receiptCancellationReasonRequired',
    'refundApprovalRequired',
    'concessionApprovalRequired',
    'scholarshipApprovalRequired',
    'allowedPaymentMethods',
  ],
  finance: [
    'fiscalYearStartMonth',
    'fiscalYearStartDay',
    'voucherApprovalRequired',
    'backdatedTransactionsAllowed',
    'futureDatedTransactionsAllowed',
    'reversalReasonRequired',
    'gstEnabled',
    'tdsEnabled',
  ],
  exams: [
    'gradingMode',
    'passingPercentage',
    'maximumMarks',
    'internalMarksEnabled',
    'practicalMarksEnabled',
    'graceMarksEnabled',
    'maximumGraceMarks',
    'revaluationEnabled',
    'rankCalculationEnabled',
    'gpaEnabled',
    'cgpaEnabled',
    'resultPublicationApprovalRequired',
    'marksDecimalPrecision',
  ],
  promotion: [
    'automaticPromotionEnabled',
    'minimumAttendancePercentage',
    'minimumPassingPercentage',
    'failedSubjectTolerance',
    'graceMarksConsidered',
    'manualPromotionOverride',
    'principalPromotionApprovalRequired',
    'promotionLockingEnabled',
  ],
  localization: [
    'defaultLanguage',
    'timezone',
    'dateFormat',
    'timeFormat',
    'currencyDisplay',
  ],
  printing: [
    'paperSize',
    'printOrientation',
    'printLanguage',
    'printShowLogo',
    'printShowAddress',
    'printShowContact',
    'printShowTimestamp',
    'printShowDocumentNumber',
    'signaturePlaceholders',
    'headerText',
    'footerText',
  ],
};

// Map Python snake_case to Prisma camelCase and vice versa
export const SNAKE_TO_CAMEL: Record<string, string> = {
  legal_name: 'legalName',
  short_name: 'shortName',
  affiliation_number: 'affiliationNumber',
  udise_code: 'udiseCode',
  primary_phone: 'primaryPhone',
  phone: 'primaryPhone',
  secondary_phone: 'secondaryPhone',
  contact_email: 'contactEmail',
  email: 'contactEmail',
  address_line_1: 'addressLine1',
  address_line_2: 'addressLine2',
  postal_code: 'postalCode',
  working_week: 'workingWeek',
  week_start: 'weekStart',
  term_naming: 'termNaming',
  roll_number_scope: 'rollNumberScope',
  academic_locking_enabled: 'academicLockingEnabled',
  student_id_format: 'studentIdFormat',
  admission_number_format: 'admissionNumberFormat',
  roll_number_format: 'rollNumberFormat',
  attendance_lock_enabled: 'attendanceLockEnabled',
  attendance_lock_hours: 'attendanceLockHours',
  attendance_correction_allowed: 'attendanceCorrectionAllowed',
  attendance_correction_reason_required: 'attendanceCorrectionReasonRequired',
  attendance_principal_override: 'attendancePrincipalOverride',
  teacher_geofence_enabled: 'teacherGeofenceEnabled',
  teacher_geofence_radius_meters: 'teacherGeofenceRadiusMeters',
  fee_currency: 'feeCurrency',
  fee_precision: 'feePrecision',
  fee_rounding_rule: 'feeRoundingRule',
  allow_partial_payment: 'allowPartialPayment',
  allow_advance_payment: 'allowAdvancePayment',
  late_fee_enabled: 'lateFeeEnabled',
  late_fee_grace_days: 'lateFeeGraceDays',
  auto_generate_receipt: 'autoGenerateReceipt',
  receipt_cancellation_reason_required: 'receiptCancellationReasonRequired',
  refund_approval_required: 'refundApprovalRequired',
  concession_approval_required: 'concessionApprovalRequired',
  scholarship_approval_required: 'scholarshipApprovalRequired',
  allowed_payment_methods: 'allowedPaymentMethods',
  fiscal_year_start_month: 'fiscalYearStartMonth',
  fiscal_year_start_day: 'fiscalYearStartDay',
  voucher_approval_required: 'voucherApprovalRequired',
  backdated_transactions_allowed: 'backdatedTransactionsAllowed',
  future_dated_transactions_allowed: 'futureDatedTransactionsAllowed',
  reversal_reason_required: 'reversalReasonRequired',
  gst_enabled: 'gstEnabled',
  tds_enabled: 'tdsEnabled',
  grading_mode: 'gradingMode',
  passing_percentage: 'passingPercentage',
  maximum_marks: 'maximumMarks',
  internal_marks_enabled: 'internalMarksEnabled',
  practical_marks_enabled: 'practicalMarksEnabled',
  grace_marks_enabled: 'graceMarksEnabled',
  maximum_grace_marks: 'maximumGraceMarks',
  revaluation_enabled: 'revaluationEnabled',
  rank_calculation_enabled: 'rankCalculationEnabled',
  gpa_enabled: 'gpaEnabled',
  cgpa_enabled: 'cgpaEnabled',
  result_publication_approval_required: 'resultPublicationApprovalRequired',
  marks_decimal_precision: 'marksDecimalPrecision',
  automatic_promotion_enabled: 'automaticPromotionEnabled',
  minimum_attendance_percentage: 'minimumAttendancePercentage',
  minimum_passing_percentage: 'minimumPassingPercentage',
  failed_subject_tolerance: 'failedSubjectTolerance',
  grace_marks_considered: 'graceMarksConsidered',
  manual_promotion_override: 'manualPromotionOverride',
  principal_promotion_approval_required: 'principalPromotionApprovalRequired',
  promotion_locking_enabled: 'promotionLockingEnabled',
  default_language: 'defaultLanguage',
  date_format: 'dateFormat',
  time_format: 'timeFormat',
  currency_display: 'currencyDisplay',
  paper_size: 'paperSize',
  print_orientation: 'printOrientation',
  print_language: 'printLanguage',
  print_show_logo: 'printShowLogo',
  print_show_address: 'printShowAddress',
  print_show_contact: 'printShowContact',
  print_show_timestamp: 'printShowTimestamp',
  print_show_document_number: 'printShowDocumentNumber',
  signature_placeholders: 'signaturePlaceholders',
  header_text: 'headerText',
  footer_text: 'footerText',
};

export const CAMEL_TO_SNAKE: Record<string, string> = {
  ...Object.fromEntries(
    Object.entries(SNAKE_TO_CAMEL).map(([s, c]) => [c, s])
  ),
  primaryPhone: 'primary_phone',
  contactEmail: 'contact_email',
};

export function validateIdentifierFormat(value: string): void {
  if (value.length > 100 || !/^[A-Za-z0-9_{}:#\-]+$/.test(value) || !value.includes('{SEQ:')) {
    throw new Error('Invalid identifier format');
  }
}
