"""Add UserRecoveryCode

Revision ID: 60da47be69f5
Revises: fbf99c8c7617
Create Date: 2026-09-02 13:45:01.942052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60da47be69f5'
down_revision: Union[str, None] = 'fbf99c8c7617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recovery_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashed_code', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_recovery_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_recovery_codes'))
    )
    op.drop_constraint('fk_user_two_factor_user_id_users', 'user_two_factor', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_two_factor_user_id_users'), 'user_two_factor', 'users', ['user_id'], ['id'])
    op.drop_column('user_two_factor', 'recovery_codes_hashed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_two_factor', sa.Column('recovery_codes_hashed', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_user_two_factor_user_id_users'), 'user_two_factor', type_='foreignkey')
    op.create_foreign_key('fk_user_two_factor_user_id_users', 'user_two_factor', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_recovery_codes')
    # ### end Alembic commands ###
